### ISSUE TITLE
Return Key Registered Every Program Start, Can't Edit Individual Key Thresholds 

### ISSUE THREAD

**Issue by Shalashaskka** [mcmonkeyprojects/KeyboardChatterBlocker#14]
Every time the program starts, it seems to register the return key, even if I remove from the configuration pannel. The configuration file doesn't seem to be updating with the program if edited that way.

Furthemore, I seem to be unable to edit the individual chatter thresholdss of any keys registered to the configure keys tab, too. I used to be able to do it by double-clicking on the tab, but that function no longer seems to be working.

**Comment by mcmonkey4eva** [comment]
`Return` key registers itself because it is (or was?) difficult to register manually (I forget the details, it's been a while, but something was going wrong with the add-key interface for some users), and auto-registering seemed the simplest/easiest way to prevent issues there. I think it might actually be an outdated issue that no longer needs the fix, and either way is superseded by the solution to issue #4 , so I'll go ahead and remove the enter key ensurer thingy.

The config file can only be reliably edited by hand when the program is closed, otherwise the program might overwrite any changes.

-----

For editing the threshold, double-clicking the current value is the way to do it, that hasn't changed.
- Make sure you're clicking on the number of the value not the whitespace next to it. Not sure why that makes a different, will probably have to fix that, but you have to be over the number value not space atm.
- Have you added a left mouse limiter? If so, that could prevent you from double-clicking. If so, you can uncheck `Enable` to let you click without restriction and then make any edits needed (including lowering the threshold on click probably to avoid the problem repeating).

**Comment by Shalashaskka** [comment]
> * Make sure you're clicking on the number of the value not the whitespace next to it. Not sure why that makes a different, will probably have to fix that, but you have to be over the number value not space atm.

I was trying that yesterday, but the program just wasn't repsonding, I suppose. I tried it today after a shutdown/bootup, and it works now. Just like you said though: only over top of the numeral.

> * Have you added a left mouse limiter? If so, that could prevent you from double-clicking. If so, you can uncheck `Enable` to let you click without restriction and then make any edits needed (including lowering the threshold on click probably to avoid the problem repeating).

I have not added that (unless there's some secret way to enable that in your program, but I don't see it :P). I guess the error had to do with the program just not being responsive. As I said, it seems to be functioning just fine today. Thanks for looking into this! 

(And also thanks for the program! It's been a massive help to handle my keyboard since it started chattering!)
