### ISSUE TITLE
Just want to say thanks!

### ISSUE THREAD

**Issue by cym104** [mcmonkeyprojects/KeyboardChatterBlocker#23]
I was using "Keyboard Chattering Fix v 0.0.1" and it has 2 very important shortcomings that you didn't mention:

1.  It doesn't work for UWP applications
2.  It doesn't work in Chrome when IME is active

Your app fixes both scenarios!

Good job!

BTW, I use 150% Windows font size, so the UI is a little corrupted （see attachment）
![微信截图_20211127080951](https://user-images.githubusercontent.com/32197077/143661967-079ab540-942c-4ae4-8721-d03cfee99a60.png)
.

**Comment by mcmonkey4eva** [comment]
So: First of all, glad to hear this helped you!

Second, regarding the bit of overlap you're seeing:
- I've updated to Windows 11 already, so that might affect testing/replication of that.
- I tested changing my display to 150%, and I didn't get that excessive overlap you showed. It might just be Win11 scales differently than Win10 does.
- I did, however, see there was a very small bit of overlap regardless of scaling, and so have moved it over to the left a bit to no longer be overlapping.
- Your fonts look... off. `Start With Windows`, ` Enable`, `Start In Tray` look more or less how they should, as does every in the log table. `Global Chatter Threshold`, and the tab names (`Chatter Log`/etc) appear to be in a completely different font? I'm not sure why that is, they're the same font in source. Which is to say, they're all the default font of "Microsoft Sans Serif, 8.5pt". This implies to me that maybe you've somehow changed your default fonts to this different font, and that might be the actual reason for the misalignment?
- `Global Chatter Threshold` is the only text in either list (the ones that are normal OR the ones that aren't) that doesn't have the default explicitly set, so I've explicitly set it to its own default value to be safe.
- I've published a new build with the slight repositioning and explicit default font setting as [Release 1.13](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.13)

If the new release still has that text mispositioned, er... well, let me know, but I'm not sure what else could be done to correct it at that point, if neither the explicit Font setting or the repositioning to not overlap at all on a normal display both don't fix it.

**Comment by cym104** [comment]
Hello!

The new release fixed the font problem!

FYI, the default UI font in Windows differs according to the installation's base language. For example, in the Simplified Chinese version of Windows 10, the default UI font is Microsoft YaHei UI.

Also, the global default UI font size can be changed without changing screen DPI. This option is at (assuming we don't want to regedit) Settings - Ease of access - Display - Enlarge text (not sure what the exact name would be in English).
