### ISSUE TITLE
Can't type diacritic when  KeyboardChatterBlocker is on

### ISSUE THREAD

**Issue by vuduc810** [mcmonkeyprojects/KeyboardChatterBlocker#33]
Yesterday I downloaded KeyboardChatterBlocker and it fixed my keyboard chatter, I was so happy. But today after turning on the computer something strange happened. I can't type letter with diacritic like á ẻ ọ... anymore https://en.wikipedia.org/wiki/Diacritic
When I try to type letter with diacritic while KeyboardChatterBlocker is enabled, nothing happens. Looking at the chatter log, the key is listed as Packet. The software I use to type letter with diacritic is EVKey, a software to type Vietnamese's characters with diacritic, I have tried using a different typing software similar to EVKey, sadly it didn't fix the problem.
Here is a short video to demonstrate what I'm trying to say: https://drive.google.com/file/d/1fOdtQalkm5m-Xi3Jrnmpap92ZN7eN4xR/view?usp=share_link

**Comment by mcmonkey4eva** [comment]
I think `Packet` is likely some form of internal signal key used by your keyboard to send those, and it's getting blocked because it looks like it's a second key pressed instantly after the last one.

So: Next to where it says `Packet` in the *Chatter Log*, there's a box that says `[Edit]` - click on that, and it will take you to the *Configure Keys* tab with `Packet` added to the list of custom keys - it should have `Chatter Threshold` set to `150` - double click on that `150`, and set it to `0` and click `Done`.

That should disable chatter detection for the `Packet` key, and thus allow you to type diacritics normally.
(It's possible that there's also something more to it that I haven't thought of, we'll see when you try it).

Let me know if that works for you!
