### ISSUE TITLE
Alternative setting for chatter detection

### ISSUE THREAD

**Issue by SevaOnOsu** [mcmonkeyprojects/KeyboardChatterBlocker#34]
My keyboard chatters when I release the key, and not when I initially press it, and from my testing the program seems to start the chatter detection timer when you press down the key. 

I think there should be an option to detect chatter upon release, or maybe an option that checks for chatter when both pressing the key down and when releasing it, and also to be able to have different thresholds for them.

**Comment by mcmonkey4eva** [comment]
Added for [(upcoming) release 1.15](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.15),

You can now edit the `config.txt` to alter `measure_from: ` to `Release` instead of `Press` to enable a mode where it measures based on the last key release, rather than the last key press.
