### ISSUE TITLE
Doesn't work in Microsoft Edge

### ISSUE THREAD

**Issue by Lager159** [mcmonkeyprojects/KeyboardChatterBlocker#35]
Hi, nice tool but doesn't work in microsoft edge for some reason, do you know the reason or a workaround?

**Comment by mcmonkey4eva** [comment]
![itworks](https://user-images.githubusercontent.com/4000772/224209575-c50c17c6-ffcc-4546-a8aa-d6fc5663b938.gif)

^ Seems to work for me. I set a high threshold on `L` to test and popped open MS Edge to the default page. Typing works normally and `L` is blocked from rapid use, exactly as expected.

There's probably something more going on in your case. Few theories:

- Is it maybe related to a specific website, rather than the browser?
- Have you maybe added some `Auto Disable Programs`, and that's being activated to automatically turn off the program when you have Edge open?
- Have you accidentally disabled it by some other means?
- Are your chatter thresholds set lower than your keyboard's chatter time, and actually it's coincidence that you first realized this in Edge?

**Comment by Lager159** [comment]
Hi, demonstration: https://i.imgur.com/fNkD4ji.gif 

However after leaving it enabled, when I started typing this answer I noticed that it does work for backspace and probably other such buttons, but doesn't work for letters and numbers, basically for the highlighted buttons it doesn't work:
![image](https://user-images.githubusercontent.com/99071479/224337900-60e7452b-30f0-4e76-b785-942aeaf81cd5.png)


I tested the input and it seems it is registering different letters but types the correct one? like this:
https://i.imgur.com/wTYYzqH.gif

Also, I am on windows 11, if that can have any effect.

So to answer your points, it happens on all websites I tested (even the search bar you tried it on), Auto disable list is empty, it is enabled (as it works for backspace) and the chatter thresholds do not apply I think, with having them set at 1000 for this demonstration

**Comment by mcmonkey4eva** [comment]
That second gif gives, uh, some amount of insight. Something's going wrong in signalling such that it's entirely reading input wrong somehow?
I wonder if it's related to language settings perhaps? As in maybe your keyboard is set to operate as a different language and that's screwing up the keycodes somehow?
I'm not sure why that would happen though, it should all be automatically handled in theory.
It's very odd that it'd be specific to Edge though either way. Does Edge have its own keyboard or language settings somewhere that you've configured?

Windows 11 is fine, I'm running win11 too.

**Comment by Lager159** [comment]
Hello, the fact that it worked for you on windows 11 edge forced me to think. Before, I automatically assumed that it was connected to edge, but now I found out it is a security feature of ESET Smart Security (Secure all browsers) 

![image](https://user-images.githubusercontent.com/99071479/224469343-5215d7cb-ce7a-4c66-824d-9d8e1a8d688a.png)


After turning it off and restarting edge process it works without problems.

With it turned on, every keystroke somehow get's recalculated to protect from keyloggers I assume? Like even if I was only pressing A, it registers a different key every press, in this order:

1234567890-= qwertyuiop[]\ asdfghjkl;' zxcvbnm,./

Anyway, thank you for this tool and for your help :)
