### ISSUE TITLE
Cannot add Tab key

### ISSUE THREAD

**Issue by doowruc** [mcmonkeyprojects/KeyboardChatterBlocker#4]
My Tab key is chattering but I am unable to add it to the Configure Keys list because it tabs through the dialog box!

**Comment by doowruc** [comment]
Tab has appeared in the Chatter Log - perhaps a right-click option in the log window to add to the Keys list, with appropriate value based on the logged delay?

**Comment by mcmonkey4eva** [comment]
Initially I was going to suggest simply editing the `config.txt` file directly for this - but that followup suggestion you posted is actually a great idea!
I've added almost exactly that (but used a double-clickable `[Edit]` button instead of right click) via the commit referenced above and publish in [Release 1.03](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.03).

Thanks for the issue report & suggested fix :D
