### ISSUE TITLE
Allow keys to be excluded from the list

### ISSUE THREAD

**Issue by omairkhawaja** [mcmonkeyprojects/KeyboardChatterBlocker#6]
Use case: I use a Logitech G810 which comes with a volume slider... I added the key and specified a custom threshold of 0 ms, but when I roll the volume slider, the key still applies numerous times in the logs:
![image](https://user-images.githubusercontent.com/3627923/80762669-f97eec00-8b0a-11ea-9daa-15b11fd1d2d1.png)

Proposal is to add either add a flag to the configure Keys tab (Exclude) or to allow a chatter threshold value to be specified that excludes the key (e.g. -1)

**Comment by mcmonkey4eva** [comment]
Wow, I didn't even think 0ms was possible for a key press speed! That's an interesting edge case there - not-a-key sending its input through as fake keystrokes.

I've patched that (via the commit referenced above) so that the `0` ms threshold will never block a keystroke, and published patch as [Release 1.04](https://github.com/mcmonkeyprojects/KeyboardChatterBlocker/releases/tag/1.04).

Thanks for the issue report :D
